### ISSUE TITLE
Orbital Jump Pad nullref related to Risky Artifacts

### ISSUE THREAD

**Issue by Moffein** [ThinkInvis/RoR2-Admiral#28]
Risky Artifacts seems to cause Admiral to nullref when setting up the Orbital Jump Pads. The skill seems to work fine in game, but it would probably be good to fix this just in case there's anything unexpected related to it.

If there's anything that needs to be done on my end regarding this, let me know.

[LogOutput.log](https://github.com/ThinkInvis/RoR2-Admiral/files/8629804/LogOutput.log)

**Comment by ThinkInvis** [comment]
This is likely because the prefabs are awakening during load, as they're only created with `GameObject.Instantiate` and not `R2API.PrefabAPI.InstantiateClone`. I'm updating the code for that to a better method that should avoid this (Addressables + InstantiateClone x2), but whatever Risky Artifacts is doing could probably stand to have more null safety added as well.

**Comment by ThinkInvis** [comment]
Should be fixed in de46abad35f390c12f13cfb78325a2ccc727fbb9.
